call pathogen#infect()
syntax enable
filetype plugin indent on

set noeb " disable error bell
set novb " don't blink the screen when there is an error
set backupext=.bak  " Append `.bak' to backups
set nocompatible
set number
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
autocmd FileType go setlocal noexpandtab shiftwidth=4 tabstop=4 softtabstop=4 nolist

:nmap \f :echo @%<CR>
:nmap \t :tabnew<CR>
:nmap \p :set paste!<CR>
:nmap \l :setlocal number!<CR>
:nmap \t <ESC>:tabnew<CR>ww
:nmap \q <ESC>:q<CR>
:nmap \w <ESC>:w<CR>
:imap \w <ESC>:w<CR>

"insert mode escape via jj
:imap jj <Esc>

"linewise up/down
:nmap j gj
:nmap k gk

"nerd tree ctrl-d toggle
map \d :execute 'NERDTreeToggle ' . getcwd()<CR>
let NERDTreeIgnore = ['\.pyc$','\.class$','\.swp$']

set wildignore+=*.swp,*.pyc,*.class

"search across files in current project - selected text
command GF :execute 'vimgrep /'.expand('<cword>').'/j '.expand(' **/*.c **/*.h **/*.java **/*.py **/*.js **/*.html **/*.rb') | copen

" Center display line after searches "
nnoremap n   nzz
nnoremap N  Nzz
nnoremap *  *zz
nnoremap #  #zz
nnoremap g* g*zz
nnoremap g# g#z

" Search for current word in new window
:nmap \v :let @/=expand("<cword>")<Bar>split<Bar>normal n<CR>
:nmap \V :let @/='\<'.expand("<cword>").'\>'<Bar>split<Bar>normal n<CR>

"delete no-yank
nnoremap R "_d

"search options
set hlsearch
set incsearch
set ignorecase
set smartcase
:nmap \ns :nohlsearch<CR>

"color accuracy in remote ssh terminals
" revisit http://vim.wikia.com/wiki/Switch_color_schemes
set t_Co=256
colorscheme jelleybeans

if has('statusline')
    "set laststatus=2
    set laststatus=0

	" Broken down into easily includeable segments
	set statusline=%<%f\    " Filename
	set statusline+=%w%h%m%r " Options
	set statusline+=\ [%{getcwd()}]          " current dir
	set statusline+=%=%-14.(%l,%c%V%)\ %p%%  " Right aligned file nav info
endif

"ruby indentation
autocmd BufNewFile,BufRead *.rb set tabstop=2
autocmd BufNewFile,BufRead *.rb set shiftwidth=2

"ask for reload
:au FileChangedShell * echo "Warning: File changed on disk"

set backspace=2 " make backspace work like most other apps


"update syntastic errors on save
let g:syntastic_always_populate_loc_list=1

"enable nice airline status line
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#show_tab_nr = 0
let g:airline#extensions#tabline#show_tab_type = 0
let g:airline#extensions#tmuxline#enabled = 1
let g:airline_theme='sol'
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#fnamemod = ':t'
if !exists('g:airline_symbols')
 let g:airline_symbols = {}
endif
let g:airline_symbols.space = "\ua0"

"low timeout for escaping
set timeoutlen=1000 ttimeoutlen=50
set cursorline

inoremap  <Up>     <NOP>
inoremap  <Down>   <NOP>
inoremap  <Left>   <NOP>
inoremap  <Right>  <NOP>
noremap   <Up>     <NOP>
noremap   <Down>   <NOP>
noremap   <Left>   <NOP>
noremap   <Right>  <NOP>

"remove trailing in python and ruby
autocmd BufWritePre *.py :%s/\s\+$//e
autocmd BufWritePre *.rb :%s/\s\+$//e
autocmd BufWritePre *.sh :%s/\s\+$//e


"golang vim settings
let g:go_fmt_command = "goimports"
let g:go_fmt_fail_silently = 1
au FileType go nmap \d <Plug>(go-def-vertical)
au FileType go nmap <Leader>i <Plug>(go-info)
au FileType go nmap <Leader>e <Plug>(go-rename)
au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)
au FileType go nmap <Leader>s <Plug>(go-implements)
au FileType go nmap <Leader>b :Tagbar<CR>

:vmap R :!psql -d $PSDB -e<enter>
