source ~/antigen/antigen.zsh

antigen use oh-my-zsh
antigen bundle git
antigen bundle pip
antigen bundle lein
antigen bundle copydir
antigen bundle copyfile
antigen bundle osx
antigen bundle command-not-found
antigen bundle tmux

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-completions src
antigen bundle MikeDacre/cdbk
antigen bundle bbenne10/goenv

antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

#antigen theme arrow

antigen apply

export TERM="xterm-256color"
#source /usr/local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin

alias ll='ls -lah'
alias h='history | grep'

export HISTSIZE=10000

unsetopt correct_all

#export PATH="$HOME/.rbenv/bin:${PATH}"
#eval "$(rbenv init -)"

export WORKON_HOME=~/Envs
export VIRTUAL_ENV_DISABLE_PROMPT=1
source /usr/local/bin/virtualenvwrapper.sh
export GOPATH=~/work/lexigram/goland
export PATH=$PATH:$GOPATH/bin

export EDITOR='vim'


export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export PYTHONPATH=.:~/.dotfiles/dots/ipython/utils
export PATH=$PATH:~/.dotfiles/bin
export LXG_PREFIX=$HOME/work/lexigram/v2

#useful alias
alias wget="curl -OL"

if [[ -f ~/.private-vars && -r ~/.private-vars ]]; then
    source ~/.private-vars
fi

alias demo_box="ssh -L 4000:localhost:9200 -L 3000:localhost:3333 -L 2000:localhost:5000 root@13.93.144.178"
