source ~/antigen/antigen.zsh

antigen use oh-my-zsh
antigen bundle git
antigen bundle pip
antigen bundle lein
antigen bundle copydir
antigen bundle copyfile
antigen bundle osx
antigen bundle tmux

antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-history-substring-search
antigen bundle zsh-users/zsh-completions src

antigen bundle mafredri/zsh-async
antigen bundle sindresorhus/pure

antigen update

antigen apply

export TERM="xterm-256color"

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin
export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/latest/bin

alias ll='ls -lah'
alias h='history | fzf'

export HISTSIZE=10000

unsetopt correct_all

export PATH=$PATH:$GOPATH/bin

export EDITOR='vim'

export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export PYTHONPATH=.:~/.dotfiles/dots/ipython/utils
export PATH=$PATH:~/.dotfiles/bin
export LXG_PREFIX=$HOME/work/lexigram/v2

#useful alias
alias wget="curl -OL"

if [[ -f ~/.private-vars && -r ~/.private-vars ]]; then
    source ~/.private-vars
fi

export FEDITOR='nvim'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Support for rbenv
eval "$(rbenv init - zsh)"

# Support for pyenv
eval "$(pyenv init -)"
