#!/bin/zsh

green='\e[0;32m'
red='\e[0;31m'
NC='\e[0m' # No Color

zmodload -ap zsh/mapfile mapfile

function runinstall {
    name=$1
    list=$2
    cmd=$3
    file_lines=( "${(f@)mapfile[$list]}" )
    linesn=$(($#file_lines - 1))
    echo "Installing $linesn $name apps ..."
    sleep 1
    for (( i = 1; i <= $linesn; i++ ))
    do
        formula=$file_lines[$i]
        echo -n "$i/$linesn $formula "
        if [[ $name = "cask" ]];then
            bout=`brew cask install $formula` 2>&1 | read berr
        else
            bout=`brew install $formula` 2>&1 | read berr
        fi
        if echo $berr | grep -qi "Error:"  ; then;
            echo -e "  ${red}[KO]${NC}"
            echo -e "  ${red}$berr${NC}"
        else
            echo -e "  ${green}[OK]${NC}"
        fi
        echo $berr >> install.log
    done
}

#tap for caskroom
brew tap caskroom/cask

runinstall "brew" "brew.list" "brew install"
runinstall "cask" "cask.list" "brew cask install"
easy_install pip
runinstall "pip" "pip.list" "pip install"

echo "installing ruby"
rbenv install 2.1.2
rbenv local 2.1.2
gem install bundler

echo "installing vim"
#vim is a bit special
brew install vim --with-python --with-ruby --with-perl --override-system-vim
